public with sharing class Constants {
	public static final String VACANCY_BUDGET_TYPE = 'Vacancy';
	public static final String ACCEPTED_STATUS = 'Accepted';
	public static final String REJECTED_STATUS = 'Rejected';
	public static final String ACCEPTED_VACANCY_ETEMPLATE_DEVNAME = 'Accepted_Vacancy_Request';
	public static final String REJECTED_REQUEST_ETEMPLATE_DEVNAME = 'Rejected_Request';
	public static final String ACCEPTED_VACANCY_EMAIL_SUBJECT = 'New Vacancy';
	public static final String REJECTED_REQUEST_EMAIL_SUBJECT = 'Request was rejected';
}